# This workflow will build the unity-sapl project

name: BuildUnitySaplProject

on:
  pull_request: {}
  push: { branches: [main] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build unity-sapl project
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      # Cache
      - uses: actions/cache@v2
        with:
          path: unity-sapl/Library
          key: Library
          
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          projectPath: unity-sapl
          unityVersion: 2021.3.11f1
          targetPlatform: StandaloneWindows64 

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        with:
          projectPath: unity-sapl
          unityVersion: 2021.3.11f1
          
      # Test Output         
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts